### ISSUE TITLE
.f command does not accept a full path in linux format

### ISSUE THREAD

**Issue by jotadepicas** [golosio/annabell#10]
If you specify a file to load for example .f /path/to/the/file.txt, the command gives an error saying `"a file name should be provided as argument."`

I guess the problem resides in annabell_main.cc, `ParseCommand` function. There the '/' character is treated specially because the macro functionality, and this seems to interfere with actual paths having that same character.
```cpp
    while (ss >> buf1) { // split line in string tokens
        if (buf1=="an") buf1="a"; // take care of article
        if (buf1=="-es") buf1="-s"; // take care of plural suffix
    
        buf = buf + buf1;
        if (buf[0]=='/' || buf[0]=='<') {
            int l=buf.size()-1;
            if ((buf[0]=='/' && buf[l]!='/') || (buf[0]=='<' && buf[l]!='>')) {
	       buf = buf + " ";
	       continue;
            }
        }
        input_token.push_back(buf);
        buf="";
    }
```
If `buf` actually contains a path with '/' characters, it will never be pushed into `input_token`, and eventually the program will fail as mentioned before.

**Comment by giorgioiavicoli** [comment]
The easiest way to go around this is probably by using a different character for the macros, like the backslash '\'

**Comment by golosio** [comment]
yes, it would probably be the easiest way, however it would require a review of all the datasets and of the manual. Another solution could be to identify commands that can work with macros. I think commands that can take paths as arguments do not need to handle macros. Let me have a look...

**Comment by golosio** [comment]
I added a few lines after the while loop.
  if (buf!="") {
    int l=buf.size()-1;
    if (buf[l]==' ') buf.erase(l);
    input_token.push_back(buf);
  }
 The problem seems to be fixed.

**Comment by jotadepicas** [comment]
I haved pulled your recent changes and indeed it is fixed. Thanks for the quick response! 

For future releases, I think this code could be refactored to something similar to the [Command Pattern](https://en.wikipedia.org/wiki/Command_pattern), converting the current "main" file into several modules, one for each command. 

In that way, you could avoid the coupling all commands have with each other in the current implementation, and every command could have overlapping syntax with no problems (for example one using the '/' character to denote a directory and the other, a macro).

However this is more than ok for a quick and effective fix, thanks!
