### ISSUE TITLE
ANNABELL for windows operating system

### ISSUE THREAD

**Issue by asemandeveloper** [golosio/annabell#17]
I am a programmer in Visual Studio. and c # programming language to write.
Your project is written for .net?

**Comment by golosio** [comment]
No, I'm sorry but it is only written for linux/unix environment.
Since you are a programmer, I also suggest that you have a look at one of my answers to Issue 1 before devoting time to this project:
https://github.com/golosio/annabell/issues/4#issuecomment-163859240
