### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [golosio/annabell#2]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/golosio/annabell/blob/94b480262f2a6b4a83f8740efed4164ddf525b67/src/annabell_main.cc#L138 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by golosio** [comment]
Done

**Comment by elfring** [comment]
Are there [a few possibilities for fine-tuning](https://github.com/golosio/annabell/blob/c7f299eb58e158b9dfaf86cd49ede4e30b85c90f/src/annabell_main.cc#L136 "Update candidate: main()") left over?
