### ISSUE TITLE
Use in MAC OS X or Windows 7

### ISSUE THREAD

**Issue by asemandeveloper** [golosio/annabell#20]
Hi and thanks for project
How i can use this project in MAC OS X?
How i can use this project with Intel Parallel Studio XE 2015 or 2016 in Windows 7?

**Comment by golosio** [comment]
I'm sorry but it is only written for linux/unix environment.
Other contributors compiled and run it in MAC OS X, however I cannot give support for this.

**Comment by jotadepicas** [comment]
@asemandeveloper I know this is an old one, but I've just pushed support for running in vagrant. I know this is not exactly support for OX X or Windows, but I found that is definitely easier to just setup a vagrant VM with the files I've just added, than going through all the hassle of compiling in a Mac/Win environment. See my PR here https://github.com/golosio/annabell/pull/34, hope it helps!
