### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [golosio/annabell#3]
Would you like to [add more error handling](https://github.com/golosio/annabell/blob/cd3dff1dab2e345fe8bc44bac43cc54e071b454e/src/ssm_cuda.cc#L35 "Update candidate: ssm_as::cuda_CopyInpuLinks()") for return values from [functions like "malloc"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")?

**Comment by golosio** [comment]
Hi Markus,
thank you for your interest in this program. Up to a few days ago it was 
only used for research purpose by a few researcher of my same team, and 
I did not care too much about (important) implementation issues, as 
those related to error handing. But now that many other researcher are 
interested in this work, for sure I'll do it as soon as possible. I know 
how to implement exception handling, I did it in other projects, just 
give me some time to do it.
Best, Bruno


On 11/14/2015 09:18 AM, Markus Elfring wrote:
>
> Would you like to add more error handling 
> <https://github.com/golosio/annabell/blob/cd3dff1dab2e345fe8bc44bac43cc54e071b454e/src/ssm_cuda.cc#L35> 
> for return values from functions like "malloc" 
> <http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/golosio/annabell/issues/3>.
>

-- 
-----
Dr. Bruno Golosio (Assistant Professor, PhD)
University of Sassari (Italy), PolComIng Department,
Section of Engineering and Information Technologies
Ph. +39 079 229587 Mob. +39 320 4220312
Home page: http://www.neuralsystems.net/~golosio/
-----

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by golosio** [comment]
I added error handling for malloc return values in dev1 branch. However note that malloc is only used for cuda version, and currently I am not able to give support for the cuda version of the code (see the manual). First I would like to improve the code and readability of the noncuda version; it will be a long work. Consider that the cuda version is designed only for improving speed of the cross validation.

**Comment by golosio** [comment]
I merged dev1 into the master branch. The issue should be fixed.
