### ISSUE TITLE
OSX - make error: use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by kilometers** [golosio/annabell#5]
Mac doesn't support `clock_gettime()`. At least three files ask for it: `annabelle_main.c`, `ssm.c` and `fssm.c`.

**Comment by kilometers** [comment]
https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb

The above code fixes this. I'm still hitting more errors, but I'll share solutions as they come.

**Comment by golosio** [comment]
Hi kilometers,
thank you for your contribution. Would it be a problem for you to make your changes in the repository so that I can merge them?
Best, Bruno

**Comment by cescobaz** [comment]
I'm also getting the same error. Merge please.

**Comment by jotadepicas** [comment]
@cescobaz  I know this is an old one, but I've just pushed support for running in vagrant. I know this is not exactly support for OX X or Windows, but I found that is definitely easier to just setup a vagrant VM with the files I've just added, than going through all the hassle of compiling in a Mac/Win environment. See my PR here #34, hope it helps!

**Comment by golosio** [comment]
In another project I used the getRealTime function provided in:
http://nadeausoftware.com/articles/2012/04/c_c_tip_how_measure_elapsed_real_time_benchmarking
which can be used freely and should work in most platforms, however I only work in linux so I was not able test it.
