### ISSUE TITLE
./make_cuda.sh not compiling

### ISSUE THREAD

**Issue by giorgioiavicoli** [golosio/annabell#6]
this is the output after trying to compile for cuda 
giorgio@giorgio-L:~/Desktop/annabell-master/src$ ./make_cuda.sh 
ssm_cuda.cu(87): warning: conversion from a string literal to "char *" is deprecated

####many lines like this, with different numbers in parentheses####

/tmp/tmpxft_00002e1f_00000000-8_annabell_main.o: In function `ParseCommand(sllm*, monitor*, std::string)':
annabell_main.cc:(.text+0x7d94): undefined reference to `simplify(sllm*, monitor*, std::vector<std::string, std::allocator<std::string> >)'
collect2: error: ld returned 1 exit status

I believe there is some problem in the creation of vector "input_token" at line 213 of annabell_main.cc

**Comment by golosio** [comment]
Sorry, currently I am not able to give support for the cuda version of the code (see the manual). First I would like to improve the code and readability of the noncuda version; it will be a long work. Consider that the cuda version is designed only for improving speed of the cross validation.

**Comment by giorgioiavicoli** [comment]
Adding comments is the worst part of the long process.

I will try to debug it and see if there's any way to fix this. I also wanted to implement OpenCL for AMD parallel processing, as I have a desktop R9 290X and it might help.

**Comment by golosio** [comment]
Thank you!

On 11/20/2015 04:25 PM, giorgioiavicoli wrote:
> Adding comments is the worst part of the long process.
>
> I will try to debug it and see if there's any way to fix this. I also 
> wanted to implement OpenCL for AMD parallel processing, as I have a 
> desktop R9 290X and it might help.
>
> On Fri, Nov 20, 2015 at 3:38 PM, golosio <notifications@github.com> wrote:
>
> > Sorry, currently I am not able to give support for the cuda version 
> of the code (see the manual). First I would like to improve the code 
> and readability of the noncuda version; it will be a long work. 
> Consider that the cuda version is designed only for improving speed of 
> the cross validation.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/golosio/annabell/issues/6#issuecomment-158418155
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/golosio/annabell/issues/6#issuecomment-158431432>.
>

-- 
-----
Dr. Bruno Golosio (Assistant Professor, PhD)
University of Sassari (Italy), PolComIng Department,
Section of Engineering and Information Technologies
Ph. +39 079 229587 Mob. +39 320 4220312
Home page: http://www.neuralsystems.net/~golosio/
-----

**Comment by golosio** [comment]
Fixed on branch dev1

**Comment by golosio** [comment]
I merged dev1 into the master branch. The problem should be fixed
